name: Deploy vpc



on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: initialize terraform
        workking-directory: vpc
        run: |
          terraform init

      - name: confirgure workspave
        workking-directory: vpc
        run: |
          terraform workspace new dev || terraform workspace select dev
  
      - name: plan
        workking-directory: vpc
        run: |
          terraform plan
                          
          
