name: Deploy vpc



on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: initialize terraform
        run: |
          terraform init
