name: deploy vpc



on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: initialize terraform
        working-directory: vpc
        run: |
          terraform init

      - name: confirgure workspave
        working-directory: vpc
        run: |
          terraform workspace new dev || terraform workspace select dev
  
      - name: plan
        working-directory: vpc
        run: |
          terraform plan
  
      - name: Apply
        working-directory: vpc
        run: |
          echo "applying"
          #terraform apply -auto-approve
                                             
               
               
          
